Revert "add XRay tracing using Natchez"
This reverts commit e6ed5cc5d10874fa08fd7f2ac691d136c74c2c37.

The implementation being reverted resulted in messages stating
java.net.SocketException: Message too long being emitted when the lambda
executes.